version: '3.1'
services:
  web_server:
    build:
      context: .
    environment:
      - EXTERNAL_PORT=${EXTERNAL_PORT}
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${EXTERNAL_PORT}"
