x-common: &common
  build:
    context: .
  environment:
    - APP_PORT=${APP_PORT}
  ports:
    - "${EXTERNAL_PORT}:${APP_PORT}"

services:
  web_server:
    <<: *common
    volumes: ${BASE_LOG_PATH:+${BASE_LOG_PATH}:${BASE_LOG_PATH}}
